name: Build e Release do Plugin

permissions:
  contents: read

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permissão ao Gradle
        run: chmod +x ./gradlew

      - name: Compilar o projeto
        run: ./gradlew build

      - name: Criar Release no GitHub com o JAR
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: build/libs/*.jar
          token: ${{ secrets.PAT_TOKEN }}
